### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by liuh236** [ezosa/M3L-topic-model#2]
Hello!
Thanks for your great job!

I find that the data folder is missing. If possible, can you release the dataset or the preprocessing script?

Thanks all.

**Comment by ezosa** [comment]
Hi!
Thank you for your message. We've added the Wikipedia article titles and image urls in our train and test sets in the data directory. We will upload the preprocessing scripts soon.

**Comment by liuh236** [comment]
thanks a lot!

**Comment by liuh236** [comment]
btw, which folder will the preprocessing scripts be placed in? ^^

**Comment by ezosa** [comment]
The utils folder

**Comment by liuh236** [comment]
> Hi! Thank you for your message. We've added the Wikipedia article titles and image urls in our train and test sets in the data directory. We will upload the preprocessing scripts soon.

- Hi! I am curious about how to extract the target text from the original Wikipedia Comparable Corpora. When will the preprocessing script be released? thanks again!

**Comment by ezosa** [comment]
Hi, 
We will upload it tomorrow.

**Comment by liuh236** [comment]
Hi, 

There is an error "tag mismatch" while using python extract titles for aligned multilingual Wikipedia articles (https://linguatools.org/tools/corpora/wikipedia-monolingual-corpora/). For example, 

` tree = ET.parse("wikicomp-2014_deen.xml") `
xml.parsers.expat.ExpatError: mismatched tag: line 58, column 31

How do you fix it?

**Comment by ezosa** [comment]
To align titles for multilingual articles, I extract titles from the crosslanguage link in the *monolingual* corpus, e.g. dewiki-20180920-corpus.xml
Monolingual corpora can be found in https://linguatools.org/tools/corpora/wikipedia-monolingual-corpora/

**Comment by liuh236** [comment]
Thanks for your response. I think there is something wrong with 2014 version (outdated) in the monolingual corpus and the 2018-version is OK. I will take a try.
