### ISSUE TITLE
MultilingualTopicModelDataPreparation seems missing

### ISSUE THREAD

**Issue by gonzalezf** [ezosa/M3L-topic-model#3]
Hi, the class "MultilingualTopicModelDataPreparation" seems missing

![image](https://user-images.githubusercontent.com/1947291/216739901-84925859-6aab-4ac5-87ac-6c77713363bc.png)

Could you provide that? I would like to run train_multilingual_contrast.py

**Comment by gonzalezf** [comment]
The class WhiteSpacePreprocessingMultilingual seems missing as well

**Comment by ezosa** [comment]
Hello,

Thank you for informing me. I've now added WhiteSpacePreprocessingMultilingual to preprocessing.py and MultilingualTopicModelDataPreparation to the data prep script.

**Comment by gonzalezf** [comment]
Thank you so much, and amazing work! :)
